PairK
bow-swift/bow pull request #651
Opened 2020-11-09 08:58 UTC by ferranpujolcamins

## Related issues

First step for #643 

## Goal

Add PairK type, product of functors.

2020-11-10 09:48 UTC, truizlop requested changes

2020-11-10 09:48 UTC, truizlop commented on Sources/Bow/Data/PairK.swift
> +extension PairKPartial: Invariant where F: Functor, G: Functor {}
This could be relaxed to F and G being Invariant.

2020-11-10 09:48 UTC, truizlop commented on Sources/Bow/Data/PairK.swift
> +extension PairKPartial: Selective where F: Monad, G: Monad {}
This could be relaxed to F and G being Selective.

2020-11-10 09:48 UTC, truizlop commented on Sources/Bow/Data/PairK.swift
> +extension PairKPartial: FunctorFilter where F: MonadFilter, G: MonadFilter {}
This could be relaxed to F and G being FunctorFilter.

2020-11-10 10:26 UTC, ferranpujolcamins commented
Fixed

2020-11-17 14:24 UTC, truizlop approved these changes
Approved, pending fixing merge conflicts.

2020-11-17 14:52 UTC, ferranpujolcamins commented
Conflicts fixed

2020-11-17 15:26 UTC, ferranpujolcamins commented
🚀

2020-11-18 08:38 UTC, merged